### ISSUE TITLE
Add Github hook for CI server

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-setup#11]
I've created [CI job](http://kotcrab.com:8080/job/gdx-setup/) on my server however to make it fully automatic @czyzby needs to create webhook. (only repository owners can do this)

1. Go to repository settings, then Webhooks.
2. Add new webhook to URL `http://kotcrab.com:8080/github-webhook/` 
3. Set content type to `application/x-www-form-urlencoded` 
4. Pick `Just the push event.`

This way new snapshot jar will be automatically build at [this location](https://dl.kotcrab.com/libgdx/gdx-setup-latest.jar) after new commit was pushed to this repository.

**Comment by czyzby** [comment]
Added. Can you check if everything's OK?

**Comment by kotcrab** [comment]
We'll see after committing something.

**Comment by kotcrab** [comment]
Build was triggered correctly, closing.
