### ISSUE TITLE
Make disabled UI elements darker

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-setup#12]
Disabled UI elements should be darker than enabled widgets. Currently they are brighter so it may confuse users. For example take a look at Android SDK path field or at FileChooser Back and Forward buttons.

**Comment by czyzby** [comment]
@kotcrab I'd like your input on the changes.

**Comment by kotcrab** [comment]
Disabled text field looks good however this change broke FileChooser navigation buttons, unnecessary `imageUp: icon-folder, imageDisabled: icon-folder-disabled `?

You can use [setGenerateDisabledImage](https://github.com/kotcrab/vis-editor/blob/master/ui/src/com/kotcrab/vis/ui/widget/VisImageButton.java#L103-L105) to automatically draw grayed version of image when button is disabled.

**Comment by kotcrab** [comment]
I've fixed this, you can close this if you think it's OK now.
