### ISSUE TITLE
VisTextArea usage refactor

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#13]
- [x] Text area should be scrollable - it must support being embedded in a scroll pane. It currently works when the scroll pane has a fixed size set by the table cell, but we'd like to support *min* size and resizeable windows. (This works only ***partially***. Maybe there should be more text area invalidations on different events.)
- [x] Read-only mode. The user should be able to select and copy text (like stack traces), but should be unable to enter or paste anything. See https://github.com/kotcrab/vis-editor/issues/175
- [x] Modify `read-only` style in `tinted.json`.
  - [x] No cursor image?
  - [x] Different font (small/[Hack](https://github.com/chrissimpkins/Hack))?
  - [x] No background?

**Comment by kotcrab** [comment]
Scrollable text area seems to work pretty well now. I tested with small and big amount of text. This also fixes that weird scroll bar jump on first window resize (by calling `dialog.invalidate()` before show).

**Comment by kotcrab** [comment]
Well I'm not sure about the font, it doesn't show code so I don't think monospaced font is needed but if you want I can change it. 'Small' font is being used already.

**Comment by czyzby** [comment]
Yes, I think the small font is OK.

I tested your changes locally and text area seems to be working as expected. Thanks.
