### ISSUE TITLE
General GUI changes

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#15]
- [x] Undecorated mode. System title bar should not be shown.
  - [x] Support application dragging.
  - [ ] Support window resizing (?).
     - [ ] Min window size.
- [x] Iconify (minimize) button.
- [x] Application icon

**Comment by kotcrab** [comment]
[2016-05-07_0955](https://cloud.githubusercontent.com/assets/4594081/15090982/e5b207ee-1439-11e6-850d-04d801ed6415.png)
On Win7 window border is still present in undercoated mode. As a side note this doesn't happen with undecorated Swing windows.

**Comment by kotcrab** [comment]
If we consider changing backend to LWJGL3 then undecorated mode should be supported properly, there is method to minimize window from code. Setting min window size will be supported in GLFW 3.2. Window dragging would have to be implemented manually. I have a felling that libgdx may report wrong mouse position when window is dragged but I think we could use GLFW to get raw mouse position.

**Comment by czyzby** [comment]
You're absolutely right, the reported mouse position when dragged is terribly off. I tried to implement dragging behavior, but the user experience is horrible (even if the input is normalized). I think we should switch to LWJGL3.

**Comment by czyzby** [comment]
Current known issues:
- Window is not resizable. Since it's undecorated, we would have to implement this functionality manually (which would solve the no-min-size-param issue: we could limit window size while doing this). I'm not sure if that's needed, so let's just put it on hold.
- Window is not draggable while a dialog is shown. Neither can you use the minimize/close icons. This is expected, as the title bar is on the same stage as the rest of the widgets. Again, I don't think it's crucial to implement, so unless issues start popping up, this can be ignored.

**Comment by kotcrab** [comment]
How about the application icon? I added it to the list. Status: GLFW does not support setting application icon, it will be added in 3.2. Alternative is to consider using JNA to invoke native APIs. I have made class that allows to do this on Windows and X11, the latter needs more testing on various distributions. If we add JNA we can also use `JNAFileDeleter` to enhance `FileChooser` UX. However JNA lib is quite big dependency, about 2MB.

**Comment by czyzby** [comment]
If you'd like to move application setting code from `VisEditor` to `gdx-setup`, I'm fine with it. However, when GLFW starts supporting icon setting, I think we should drop the JNA dependency - is there any reason why `JNAFileDeleter` is superior to the default one?

**Comment by kotcrab** [comment]
`JNAFileDeleter` supports moving files to system trash instead of deleting them permanently. I think that this is more expected behavior from file chooser than deleting files permanently.

**Comment by czyzby** [comment]
> A few more points (Reference: Java Concurrency in Practice)
> 
> When a new thread is created it inherits the daemon status of its parent.
> 
> Normal thread and daemon threads differ in what happens when they exit. When the JVM halts any remaining daemon threads are abandoned:
> - finally blocks are not executed,
> - stacks are not unwound - the JVM just exits.
> 
>Due to this reason daemon threads should be used sparingly and it is dangerous to use them for tasks that might perform any sort of I/O.

[Source](http://stackoverflow.com/questions/2213340/what-is-daemon-thread-in-java). They are called background threads for a reason.

**Comment by czyzby** [comment]
`gdx-setup` is already pretty big. I don't think that we should include another dependency *permanently*, especially since it will be removed as soon as "native" support for application icons will be added. The "clear folder" utility is more convenient anyway (`FileChooser` supports only a single deletion at a time - which is to be expected, since we don't use it in multi-select mode).

**Comment by kotcrab** [comment]
I agree on dropping JNA once GLFW supports icons but It might take some time to have GLFW updated. First there have to release new GLFW version, then LWJGL3 has to update and release new version and finally libgdx backend needs to update to newer LWJGL3.

I can add icon changer from vis-editor but first I have to setup Mint VM. Unless you want to help me with debugging that, in that case I can push it to new branch so you can test it.

**Comment by tommyettinger** [comment]
Tooltip descriptions that appear on hover don't last long enough for me to read them sometimes. I've had cases where every tooltip on a screen vanishes after a second or less, and other cases where the tooltip stays up until I move the mouse (which I would expect for behavior). Not sure what causes that, if it's in the gdx-setup code or if it's my laptop trackpad being weird and sending very slight movement frequently. This is merely annoying, I wouldn't consider it a serious bug.

**Comment by kotcrab** [comment]
Interesting. You are right, tooltips will disappear even after slight movement. I see how this can be annoying to trackpad users. I'll add some kind of bounds check to allow small mouse movement after showing tooltip. See https://github.com/kotcrab/vis-editor/issues/180

**Comment by kotcrab** [comment]
Tooltips now don't fade out on mouse move. No change is needed on gdx-setup side.

**Comment by kotcrab** [comment]
Application icon is now supported on Windows and *some* graphical platforms using X11.

**Comment by czyzby** [comment]
I'm afraid this is as far as we can get until GLFW includes the *proper* way to do this. Good job.

**Comment by czyzby** [comment]
Actually, since undecorated mode works pretty good, I don't think that the window resizing is absolutely necessary. I'm closing this issue for now, but I'm willing to open it again if people start screaming.

**Comment by intrigus** [comment]
GLFW already includes the _proper_ way to do it. The problem is that libgdx's LWJGL/GLFW version is outdated.

**Comment by czyzby** [comment]
Fixed. ;)

**Comment by kotcrab** [comment]
@intrigus It has milestone for GLFW 3.2 which wasn't even released yet. I'm sure it will take long time to have LWJGL and libGDX update. And well this is *proper* way, same native APIs are being called underneath.

**Comment by czyzby** [comment]
Let's go with "standardized" instead of "proper". Some day in the future we can drop the additional dependency and let GLFW handle icon changing.
