### ISSUE TITLE
Application does not exit after generating project

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-setup#17]
After generating project and closing main window app process is still running, Maybe Executor is not being shutdown properly?

**Comment by czyzby** [comment]
I don't think that the executor threads should be daemons, since they actually do the hard work in the application. If anything, the rendering is not that important when generating projects data.

Anyway, since I never had this problem in the first place, can you check if the application exists properly after I added destruction method?

**Comment by kotcrab** [comment]
Yes it exits correctly. I think this became problem after switching to LJWGL3 - I think LWJGL2 uses more *drastic* exit procedure.

> I don't think that the executor threads should be daemons, since they actually do the hard work in the application. If anything, the rendering is not that important when generating projects data.

Well you are calling `shutdownNow` anyways - this actively tries to shutdown all running tasks. Use `shutdown` if you want to allow running tasks to finish.

**Comment by czyzby** [comment]
If the user - for whatever reason - closes the application during generation, he should expect errors in this project. I can imagine that one would like to "kill" and restart his application when running some unfortunate Gradle task (like `dist` on GWT, which takes up to several minutes). This isn't much different from the daemon approach (the application closes immediately), but now the executor thread is as "important" for the JVM as the rendering thread, so there won't be any strange problems on slow, one core CPUs where the generation is super-slow/never finishes.

**Comment by kotcrab** [comment]
I see, I didn't know daemon threads affect performance, I though they only don't prevent JVM from exiting if they are still running.

**Comment by czyzby** [comment]
> A few more points (Reference: Java Concurrency in Practice)
> 
> When a new thread is created it inherits the daemon status of its parent.
> 
> Normal thread and daemon threads differ in what happens when they exit. When the JVM halts any remaining daemon threads are abandoned:
> - finally blocks are not executed,
> - stacks are not unwound - the JVM just exits.
> 
>Due to this reason daemon threads should be used sparingly and it is dangerous to use them for tasks that might perform any sort of I/O.

[Source](http://stackoverflow.com/questions/2213340/what-is-daemon-thread-in-java). They are called background threads for a reason.
