### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-setup#21]
It would be good idea to add update checker checking for newer version of gdx-setup. This can implemented in very simple way, there would be one text file with latest version URL either in this repository or on GtiHub pages. If newer version is found then dialog would be displayed (or less obstructive notification somewhere in the main window) and upon clicking on it user would be taken to that URL to download new jar - so no auto updater but that also can be considered. 

With original gdx-setup I was always downloading new jar when I wanted to create new project. You never new when there was a new version. This setup uses versions but still it would be a lot nicer to have updates shown in the UI instead of need to go here to check for new version.

**Comment by czyzby** [comment]
A toast with a link to releases is displayed if your current version doesn't match the latest release. I think it would be nicer if it was displayed on the bottom of the screen (it covers the LibGDX logo), but `ToastManager` currently does not support alignment. @kotcrab - check if it's OK.

**Comment by kotcrab** [comment]
Looks OK, I'll handle the alignment in `ToastManager`. Let's leave this open.

**Comment by kotcrab** [comment]
Setting toast alignment is now supported.
