### ISSUE TITLE
Add iOS backend support

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#26]
- [x] Include `iOS` platform.
- [x] Add iOS-specific libraries.
- [x] Include iOS launchers in project templates.
- [x] Include RoboVM version in advanced settings.

**Comment by czyzby** [comment]
@kotcrab Can you test this?

**Comment by kotcrab** [comment]
It imported into IDEA fine on Windows. I guess I can't test anything more on Windows, right?

@intrigus could you help us test project generation on Mac?

**Comment by czyzby** [comment]
I don't think so, no. At least you can import/modify it on Windows and Linux without any problems, that's something.

**Comment by intrigus** [comment]
Everything works fine via Eclipse and cli.
@czyzby Could you (as an exchange) have a look at https://github.com/libgdx/libgdx/pull/4084 ?

**Comment by czyzby** [comment]
Great, thanks.

Do you want to me to test these or do a code review? I cannot merge it into the main repo (obviously), and I'm pretty sure there's not much difference between, say, Chrome on Windows and on Linux. I've looked through the code and have some minor suggestions, but it looks fine.

**Comment by czyzby** [comment]
Since the generated projects are pretty much the same as the ones from the official `gdx-setup` and iOS project was tested, I'm closing this issue for now. Don't hesitate to comment/reopen if there are any bugs in the RoboVM project generation.

**Comment by intrigus** [comment]
@czyzby Thanks for you review and your 👍  on the issue :)

Waiting for MOE support :)

**Comment by czyzby** [comment]
You can watch the progress in #27. I want to include some checks if MOE is properly installed, but - unfortunately - there's no Linux support yet, so I might have to leave this one for @kotcrab or set up a VM. This might take a while (~week?).

**Comment by czyzby** [comment]
https://github.com/libgdx/libgdx/issues/3866
