### ISSUE TITLE
Add MOE backend support

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#27]
- [x] Include `MOE` platform.
- [x] Add MOE-specific libraries.
- [x] Include iOS MOE launchers in project templates.
- [x] Include MOE version in advanced settings.
- [x] Check if MOE is installed. Add warning (and disable form?) if backend is chosen, but MOE is not installed locally.

**Comment by kotcrab** [comment]
@czyzby checkout `moe` branch. Imports cleanly with Android Studio with MOE installed. I'm afraid that's all I can check. When I try to create launch configuration I get error "it is for Mac only".

There is not enough space in Advanced tab, not sure what to do with it. You can just increase app height I think.

What you mean by "Add MOE-specific libraries."?

**Comment by czyzby** [comment]
> What you mean by "Add MOE-specific libraries."?

Natives for extensions like Box2D and so on. I think I already added these along with the RoboVM backend, as most were duplicated.

> There is not enough space in Advanced tab, not sure what to do with it. You can just increase app height I think.
`ScrollPane`?

**Comment by czyzby** [comment]
Merge https://github.com/czyzby/gdx-setup/commit/db5453cf3425b364f0358eb570a44dce1e65f2fe - it should be fine. I think we can merge it with master after you replace the images with their equivalents from `generator/ios` - they seem to be roughly the same.

**Comment by kotcrab** [comment]
Damn forgot about the images, I'll fix that.

**Comment by kotcrab** [comment]
Alright, done. We can close this after somebody confirms it's working. @intrigus could you do some testing?

**Comment by intrigus** [comment]
Will try it tomorrow.

**Comment by czyzby** [comment]
Tested and seems to be working, reopen or comment if any errors occur.
