### ISSUE TITLE
Add alternative desktop platforms

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#28]
- [ ] JGLFW.
- [ ] LWJGL 3.

**Comment by czyzby** [comment]
Loading music throws exception on Linux, I think this is related to: https://github.com/badlogic/jglfw/issues/2

@kotcrab Can you check if the backends are relatively stable on Windows?

**Comment by kotcrab** [comment]
I've never heard of anyone using JGLFW to be honest. Both LWJGL 3 and JGLFW import into Intellij and run cleanly with VisUI showcase template.

**Comment by intrigus** [comment]
JGLFW is only used on Mac by [Spine](http://esotericsoftware.com/).

**Comment by czyzby** [comment]
It's not checked on by default, neither is it affected by the "toggle clients" button. Unless LibGDX devs ditch it completely, it should be available. I think giving people an alternative is always nice, even if there are superior options - to be honest, I didn't even know about this backend before I started working on `gdx-setup`.
