### ISSUE TITLE
kotlin templates

### ISSUE THREAD

**Issue by sreich** [czyzby/gdx-setup#32]
kotlin template for applicationlistener/adapter, seems to create a java class instead. what it should do is create a kotlin one for starters.

**Comment by czyzby** [comment]
Kotlin is not supported by GWT, which means you cannot target HTML5/WebGL backend. LibGDX itself is written in Java - I'd say that Java is still the default language, and all templates certainly _should not_ be (solely) in Kotlin. With a decent Java-to-Kotlin code converter, starting with a Java project and converting it "manually" is not really that bad.

However, all project templates contributions are welcome. We would certainly accept and PRs with Kotlin code templates.

**Comment by sreich** [comment]
No, not at all what I meant to imply. Just that for a language selected, and am additional option(like vis ui etc), it should be in that language.

Of course that'll require a bit of work. 

And probably I think the Java ones need improved firstly, specifically the starter options..there doesn't seem to be one for "libgdx game with scene2d". There's a visui one though,which did suit my needs in this case. But alas,this is a different issue.

**Comment by czyzby** [comment]
By "a bit of work" you mean rewriting every template in every extra language we support. That's probably not going to happen. I don't think I'm even confident enough with Scala to do this right.

Most starter templates aim to be as simple as possible or showcase some library API. Games with too much assets could make the gdx-setup application too big. However, we welcome all contributions.

**Comment by sreich** [comment]
I was not referring to anything more than a simple equivalent of the visui example,minus the visui for those who want scene2d instead

**Comment by czyzby** [comment]
Official `gdx-setup` has only 1 project template, which isn't a showcase of LibGDX by any means. The templates we marked as "official" are just that: simple API usage to get you started. It is assumed that the user already knows LibGDX API, more or less.

"Unofficial" project templates are showcases of _external_ libraries, which might not be as well known as the official ones. This is the only reason they are much more complex - it's hard to use extensions without seeing them in action first.

However, Scene2D, controllers and Box2D API showcases could certainly be nice.

**Comment by czyzby** [comment]
See #38. Since we (together with @kotcrab) prepared some LibGDX Kotlin utilities - [KTX](https://github.com/czyzby/ktx) - it's likely we'll add some Kotlin project templates to showcase its usage.
