### ISSUE TITLE
Add Joise as third-party extension

### ISSUE THREAD

**Issue by BenMcLean** [czyzby/gdx-setup#41]
The new [Joise 1.0.3](https://github.com/SudoPlayGames/Joise) is now GWT-compatible and it would be nice to include it. The major advantage Joise has (for me at least) over SquidLib (which I'm also using) and Noise4J is that Joise can do seamless a.k.a. wrapping a.k.a. repeating noise.

**Comment by czyzby** [comment]
Never really got a chance to use SquidLibg, but it does look much more feature-complete than Noise4J. I'll look into it.

**Comment by czyzby** [comment]
I'm having trouble downloading the library and it currently seems to be [unavailable](http://mvnrepository.com/search?q=joice) on Maven Central.

![joice](https://cloud.githubusercontent.com/assets/11707612/21750783/90922278-d5bb-11e6-9ddf-602ddb431667.png)
![joice2](https://cloud.githubusercontent.com/assets/11707612/21750790/a43928f8-d5bb-11e6-9b0d-508ec070a7e1.png)

Any ideas?

**Comment by BenMcLean** [comment]
Sure you spelled it right? It's Joise not Joice.

**Comment by czyzby** [comment]
...I'm too tired for this job. You're absolutely right.

**Comment by czyzby** [comment]
OK, GWT project seemed to compile successfully with this library. Thanks for your suggestion and sorry for the silly typo. ; )
