### ISSUE TITLE
Generated GWT projects fail in browser due to outdated JS

### ISSUE THREAD

**Issue by tommyettinger** [czyzby/gdx-setup#46]
The official libGDX setup tool recently updated a specific file, [soundmanager2-jsmin.js](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-setup/src/com/badlogic/gdx/setup/resources/html/war/soundmanager2-jsmin.js), to the most recent version as part of the libGDX 1.9.5 and GWT 2.8.0 update. The problem is, if an application uses libGDX 1.9.5 or 1.9.6 but has a soundmanager2-jsmin.js file from an earlier version, then there's a mismatch when the app is loaded in the browser and the entire application fails to start. This file isn't part of the jar distribution or anything, and needs to be added as part of the project generation to the `webapp` folder of the gwt module. I've gotten around this by copying in that file manually, which works OK... but the user should at least be told they need to copy in that file to (using this tool's layout conventions) `gwt/webapp/soundmanager2-jsmin.js` . The main tricky part to fixing this in gdx-setup is using a different soundmanager2-jsmin.js for libGDX 1.9.4 or earlier versus 1.9.5 or later.

In order to compile on GWT 2.8.0, I've also needed to remove the line

```
enableClosureCompiler = true
```

from `gwt/build.gradle`, since that option isn't present in GWT 2.8.0, and to add the line

```
<set-configuration-property name="xsiframe.failIfScriptTag" value="FALSE"/>
```

to the file GdxDefinition.gwt.xml (which is in the user-specified package folder in the gwt module).
These are definitely needed for the `gwt:dist` task, but I don't know if they're needed for superDev. I may have missed some steps, but I have a working project in https://github.com/tommyettinger/SquidLib-Demos/tree/master/TheTsar3 that I can check for changes I made.

**Comment by czyzby** [comment]
Thanks.

**Comment by tommyettinger** [comment]
No, thank you! I think this is the first "somewhat-of-an-inconvenience"-level bug I've encountered with gdx-setup as a user, which is more than I can say of the official setup. I think I should be able to recommend this setup tool over the standard libGDX one to users of my library [SquidLib](https://github.com/SquidPony/SquidLib). That lets me avoid the ugliness of the custom setup tool attempt I was doing, once I figure out a good way to handle the optional (but recommended) assets.

**Comment by czyzby** [comment]
Yeah, I wish stuff like SoundManager was in the classpath, since it's a part of the codebase. Now I have to recreate some sort of versioning system and put the correct library for each LibGDX version. I'll look into it later today and push another beta release.

**Comment by czyzby** [comment]
There. I really didn't want to have to check LibGDX version and include different SoundManager sources, but there it is. It seems to work for both latest version (1.9.6) and older ones (pre-1.9.4) - provided you choose the correct GWT version. You can check out the latest beta release.

**Comment by tommyettinger** [comment]
Thanks! Will do.
