### ISSUE TITLE
Output stream not shown in Intellij run tab

### ISSUE THREAD

**Issue by xaguzman** [czyzby/gdx-setup#47]
I created a project using this tool, and everything is smooth!

The only thing that is affecting me is the fact that the project created with the tool will not display calls to Gdx.app.log, or System.out.println in the "run tab", making it quite dificult to debug at times.

I am quite sure this is related to the project, as my previous project (created with the official tool) is able to display the output without problems (using the same intellijidea version and in the same computer).

I have already enabled the "Show console when a message is printed to standard output stream" to see if it made any difference, but didn't work.

I checked the desktop build.gradle to compare it to the ones created by the original setup tool, but there doesn't seem to be anything there which could be causing this trouble.

Any idea on how to overcome this?

**Comment by czyzby** [comment]
I don't think this is a gdx-setup issue and I have never encountered a bug like this. Off the top of my head:
* Have you checked the run configuration of the desktop project? Maybe standard output if somehow blocked.
* If you changed LibGDX `Application` logging level, `Gdx.app.log` calls might be ignored.
* Have you tried overriding `System.out` somehow? Not something you usually do, but I think reflection could handle it.
* Have you tried ~~turning it off and on again~~ recreating the project? Does it happen on both desktop (LWJGL 2) and LWJGL 3?

**Comment by xaguzman** [comment]
I have no idea what happened, I just reimported the project in intellijidea and now the output seems to be working...
Thanks for the suggestions though!

**Comment by czyzby** [comment]
Glad it works.
