### ISSUE TITLE
Can't create project with ios-MOE

### ISSUE THREAD

**Issue by NathanMBui** [czyzby/gdx-setup#48]
I followed the instruction in official MOE website (install eclipse plugin then create a project) to install MOE on my mac. But still can not check the "ios MOE" platform. It keep prompt "Intel's Multi OS Engine is not installed"

**Comment by czyzby** [comment]
@kotcrab Can you check this out?

**Comment by czyzby** [comment]
@NathanMBui This is the check performed to see if MOE is installed: `if (System.getenv("INTEL_MULTI_OS_ENGINE_HOME") == null)`. The property name might have been changed, is different on Mac or simply incorrectly set in your case. We need to investigate it further, but for now - as a workaround - please [set environment variable manually](https://stackoverflow.com/questions/7501678/set-environment-variables-on-mac-os-x-lion).

**Comment by NathanMBui** [comment]
Thanks for your quick replies
Don't know if this is actually the path to set environment variable:
"/Users/NathanBui/.moe/moe-sdk-1.3.6"
It contains 2 folder: sdk and tools
so I add these line to bash_profile: 
export INTEL_MULTI_OS_ENGINE_HOME=/Users/NathanBui/.moe/moe-sdk-1.3.6/sdk
export PATH=${INTEL_MULTI_OS_ENGINE_HOME}:$PATH

It said "//moe: No such file or directory"

**Comment by czyzby** [comment]
I'm unfamiliar with Macs, to be honest. However, I don't think you need this line, unless you want to execute some programs from MOE home directory (which I doubt):
`export PATH=${INTEL_MULTI_OS_ENGINE_HOME}:$PATH`

Try creating both `.profile` and `.bash_profile` files (note the dot!) with this content:
`export INTEL_MULTI_OS_ENGINE_HOME=/Users/NathanBui/.moe/moe-sdk-1.3.6`
The thread I posted lists ways to reload the variables, but you can relog (or reboot?) to make sure the properties are fully refreshed.

**Comment by NathanMBui** [comment]
I successfully set the environment, restart to make sure it affect. then use the command "printenv" to check again. so it in environment now: INTEL_MULTI_OS_ENGINE_HOME=/Users/NathanBui/.moe/moe-sdk-1.3.6

**Comment by czyzby** [comment]
OK, does `gdx-setup` work as expected with the variable in place?

**Comment by czyzby** [comment]
1. Can you run `gdx-setup` from command line to see if it helps? `java -jar gdx-setup.jar`.
2. Can you run this simple Java application to see if the environment variable is read correctly?

```Java
public class Test {
  public static void main(String[] args) {
    System.out.println(System.getenv("INTEL_MULTI_OS_ENGINE_HOME"));
  }
}
```

If it prints `null`, Java has problem reading your environment variables.

**Comment by NathanMBui** [comment]
1. Ok it let me check the button. thanks for your help and patient.
2. Java does return null

**Comment by NathanMBui** [comment]
PS: I have checked other variables and java return null all of them. maybe something wrong with java / OS X / Eclipse ??

**Comment by kotcrab** [comment]
@czyzby This variable seems to be no longer important in MOE. Similar check was removed in original gdx-setup in commit https://github.com/libgdx/libgdx/commit/429bd1d6356054294a8f5a3ed7ec93f9773a3998. 
Looks like it was replaced by `MOE_HOME` but the check was removed anyways.

We are also using old version `1.1.0.final-1`, we need to update to `1.3.2`. 
It requires changing setup project files. Reference https://github.com/libgdx/libgdx/pull/4563.
Also see [changes to libgdx's gdx-setup](https://github.com/libgdx/libgdx/commits/master/extensions/gdx-setup/src/com/badlogic/gdx/setup ) but after quick check I'm not seeing any bigger changes than this pull request.

**Comment by czyzby** [comment]
@kotcrab Can you update MOE project generation in `gdx-setup`?

**Comment by kotcrab** [comment]
@czyzby Ok, I will do it tomorrow

**Comment by czyzby** [comment]
Thanks, much appreciated.

**Comment by kotcrab** [comment]
Done, updated to `1.3.2`.

@NathanMBui Download latest [snapshot](https://dl.kotcrab.com/libgdx/gdx-setup-latest.jar) and try generating project. I'd appreciate if you could also try to fully build it using XCode.

**Comment by czyzby** [comment]
@kotcrab Thank you!

@NathanMBui I'll close the issue once you confirm that you have no problem generating and running iOS MOE project using the latest snapshot release.

**Comment by NathanMBui** [comment]
I generated new project but can't build using gradle or xcode (I didn't change anything). here is the error:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/NathanBui/Documents/Workspace/Projects/chess24h/TestMoe/ios-moe/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':ios-moe'.
> Could not find method moe() for arguments [build_1zucm5qwe4h7jzja1lwrq3161$_run_closure3@da82f47] on project ':ios-moe' of type org.gradle.api.Project.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':ios-moe'.

root's build.gradle:
`
buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
  }
  dependencies {
    classpath "com.badlogicgames.gdx:gdx-tools:$gdxVersion"
    classpath "org.multi-os-engine:moe-gradle:$moeVersion"
  }
}

allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'
}

configure(subprojects) {
  apply plugin: 'java'
  sourceCompatibility = 1.6
}

subprojects {
  version = '0.0.1-SNAPSHOT'
  ext.appName = 'TestGdxSetup'
  repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
  }
}

// Clearing Eclipse project data in root folder:
tasks.eclipse.doLast {
  delete '.project'
  delete '.classpath'
  delete '.settings/'
}
`

moe's build.gradle:
`
// Exclude all files from Gradle's test runner
test { exclude '**' }

task copyNatives << {
    file("xcode/native/ios/").mkdirs();
    def LD_FLAGS = "LIBGDX_NATIVES = "
    configurations.natives.files.each { jar->
        def outputDir = null
        if (jar.name.endsWith("natives-ios.jar")) outputDir = file("xcode/native/ios")
        if (outputDir != null) {
            FileCollection fileCollection = zipTree(jar)
            for (File libFile : fileCollection) {
                if (libFile.getAbsolutePath().endsWith(".a") && !libFile.getAbsolutePath().contains("/tvos/")) {
                    copy {
                        from libFile.getAbsolutePath()
                        into outputDir
                    }
                    LD_FLAGS += " -force_load \${SRCROOT}/native/ios/" + libFile.getName()
                }
            }
        }
    }
    def outFlags = file("xcode/ios-moe/custom.xcconfig");
    outFlags.write LD_FLAGS

    def proguard = file("proguard.append.cfg")
    if (!proguard.exists()) {
        proguard = new File("proguard.append.cfg")
        proguard << "\n-keep class com.badlogic.** { *; }\n"
        proguard << "-keep enum com.badlogic.** { *; }\n"
    }
}

sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.resources.srcDirs = [ file("../assets") ]

// Setup Multi-OS Engine
moe {
    xcode {
        project 'xcode/ios-moe.xcodeproj'
        mainTarget 'ios-moe'
        testTarget 'ios-moe-Test'
    }
}

moeMainReleaseIphoneosXcodeBuild.dependsOn copyNatives
moeMainDebugIphoneosXcodeBuild.dependsOn copyNatives
moeMainReleaseIphonesimulatorXcodeBuild.dependsOn copyNatives
moeMainDebugIphonesimulatorXcodeBuild.dependsOn copyNatives

// Setup Eclipse
eclipse {
    // Set Multi-OS Engine nature
    project {
        natures 'org.multi-os-engine.project'
    }
}

dependencies {
  configurations { natives }

  compile project(':core')
  compile "com.badlogicgames.gdx:gdx-backend-moe:$gdxVersion"
  compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
}
`

**Comment by kotcrab** [comment]
I think we are missing `apply plugin: "moe"` from MOE `build.gradle`. Try adding it at the top.

**Comment by czyzby** [comment]
@kotcrab I can be wrong, but Gradle MOE plugin seems to be missing. I think we went for plugins inside project Gradle files - official `gdx-setup` keeps them inside the root Gradle file, so you could have missed it.

**Comment by czyzby** [comment]
@kotcrab 
https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/data/platforms/android.kt#L20
https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/data/platforms/android.kt#L90

**Comment by kotcrab** [comment]
@czyzby MOE plugin was added to `buildscript` dependencies but it was missing `apply plugin` declaration from module `build.gradle`. Sorry for this, my "Mac" randomly stops downloading dependencies so it's hard to test.

@NathanMBui please try new snapshot (same link) or manually add `apply plugin: 'moe'` to `ios-moe/build.gradle`

**Comment by NathanMBui** [comment]
build using gradle is ok but error on xcode:
ld: file not found: /Users/NathanBui/Documents/Workspace/Projects/chess24h/TestMoe/ios-moe/xcode/native/ios/libObjectAL.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

xcode: 8.3.1
ios SDK: 10.3

**Comment by kotcrab** [comment]
@NathanMBui Hmm I'm getting same error when building project generated from official gdx-setup

**Comment by czyzby** [comment]
GREAT, THEN IT'S FIXED.

**Comment by kotcrab** [comment]
Looks like you need to call `gradlew copyNatives` before building for first time. No idea where it is documented in libgdx wiki.

**Comment by NathanMBui** [comment]
It works. Another question: How can I run it in eclipse?. I imported project as a Gradle but can not run as a MOE project. I have installed MOE plugin and be able to create a MOE project

**Comment by czyzby** [comment]
> It works.

I'm glad it finally worked - I'm going to close this issue for now, but if you have any problems with the generated iOS projects, don't hesitate to reopen.

> How can I run it in eclipse?

I think we're both using IntelliJ, so I'm afraid you'll have to figure it out yourself. Since the generated project should roughly match official LibGDX structure, you can ask this question on the [official forum](http://www.badlogicgames.com/forum/) or IRC.

Thanks for reporting the bug.

**Comment by kotcrab** [comment]
I pushed one more commit with fixes. We are using standard source set so no need to change that and I fixed adding native dependency. Without this build would succeed but app would fail at runtime.

You actually don't have to use XCode for building, it must be installed but you can run build from Java IDE.
In case of IntelliJ you will have MOE launch configuration by default so just press Launch button and it will build app and start iPhone emulator.
