### ISSUE TITLE
VisEditor-related templates

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#6]
- [x] VisUI: basic usage. (How to include VisUI in an actual project?)
- [x] VisUI: widget showcase.
- [x] VisEditor: basic usage. (How to load a VisEditor scene and use it in an application?)
- [x] ~~VisEditor: simple game.~~

**Comment by kotcrab** [comment]
Added showcase template in https://github.com/czyzby/gdx-setup/commit/3a252af5b73f17527078bbf1571166a8955c911c (forgot to mention issue).

**Comment by czyzby** [comment]
Maybe you should consider removing/commenting out `FileChooser` code. It's likely to crash on GWT, it would be nice if the demo worked on every platform.

**Comment by kotcrab** [comment]
Right, I'll remove it. Too bad file chooser is one of the nicest widgets.

**Comment by czyzby** [comment]
I suggest leaving it as a comment. Anyone going through the code should find and test it without any problems.

**Comment by kotcrab** [comment]
@czyzby added basic template, would you care to check?
It shows basic example how to load exported project and how to include custom system into scene. It also copies project files that can be opened in VisEditor.

**Comment by czyzby** [comment]
Great, I think it's more than enough to get you started - I'd just change the atlas filter settings to improve the scaling.
