### ISSUE TITLE
jglfw project doesn't compile

### ISSUE THREAD

**Issue by DavidPartouche** [czyzby/gdx-setup#62]
the last version of `gdx-backend-jglfw` is `1.9.6`, while setting up a project for it tries to compile `$gdxVersion` (`1.9.8`). So Maven can't find the package.

In the backlog of libGDX 1.9.7 it says:
> - API Change: removed JGLFW backend
So we should we remove it from gdx-setup also?

**Comment by czyzby** [comment]
Definitely.
