### ISSUE TITLE
Wrong url for KtxGraphics

### ISSUE THREAD

**Issue by georgwarden** [czyzby/gdx-setup#68]
[This link](https://github.com/czyzby/gdx-setup/blob/45a0d457833c5fe7e82f8701129ec64707f592bb/src/main/kotlin/com/github/czyzby/setup/data/libs/unofficial/ktx.kt#L253) under KtxGraphics definition actually directs to KtxStyle. I don't really think it's expected behavior, right?

**Comment by czyzby** [comment]
It's not. Thanks!
