### ISSUE TITLE
USL extension

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-setup#9]
- [x] Added to third-party extensions.
- [x] ~~Simple project template. *Is it necessary though?*~~
- [x] Gradle task, simple `.usl` file included in `raw` folder.
  - [x] Translate the default skin file to USL, so it could be used along with the `pack` task.

USL is an alternative to plain LibGDX skin JSON files. It could be easily added as a Gradle build time dependency and invoked via Gradle task, similarly to [texture packer](https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/data/project/project.kt#L114-L125). Providing a separate USL template might be unnecessary - it's not really a runtime extension, I think such template would simply consist of JSON generation at headless and desktop projects.

As a third party extension, USL should be added to root Gradle build time dependencies (`project.rootGradle.buildDependencies`) with quotes included. Including it as compile time dependency in desktop and headless projects - similarly to `gdx-tools` - might also prove useful.

**Comment by kotcrab** [comment]
@czyzby Please check `usl` branch.

I agree that example project is unnecessary. Not sure about adding it to headless or desktop project. USL doesn't have classes that might be useful from source code for standard user that just want to compile USL to JSON.

**Comment by czyzby** [comment]
It seems to work correctly, but there's no description of the extra USL tasks when generating a project with README. For example, `pack` task [adds this description](https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/data/project/project.kt#L157-L158):
```
- `pack`: packs GUI assets from `raw/ui`. Saves the atlas file at `assets/ui`.
```

**Comment by kotcrab** [comment]
Ops, completely missed tasks descriptions, should be good now.
